// Copyright (c) The nextest Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

use crate::{
    errors::{EnvVarError, SetupScriptOutputError},
    reporter::events::SetupScriptEnvMap,
};
use camino::Utf8Path;
use regex::Regex;
use std::{
    collections::BTreeMap,
    sync::{Arc, LazyLock},
};
use tokio::io::{AsyncBufReadExt, BufReader};

/// Parses an environment file generated by a setup script.
pub(super) async fn parse_env_file(
    env_path: &Utf8Path,
) -> Result<SetupScriptEnvMap, SetupScriptOutputError> {
    let mut env_map = BTreeMap::new();
    let f = tokio::fs::File::open(env_path).await.map_err(|error| {
        SetupScriptOutputError::EnvFileOpen {
            path: env_path.to_owned(),
            error: Arc::new(error),
        }
    })?;
    let reader = BufReader::new(f);
    let mut lines = reader.lines();
    loop {
        let line =
            lines
                .next_line()
                .await
                .map_err(|error| SetupScriptOutputError::EnvFileRead {
                    path: env_path.to_owned(),
                    error: Arc::new(error),
                })?;
        let Some(line) = line else { break };

        // Split this line into key and value.
        let (key, value) = match line.split_once('=') {
            Some((key, value)) => (key, value),
            None => {
                return Err(SetupScriptOutputError::EnvFileParse {
                    path: env_path.to_owned(),
                    line: line.to_owned(),
                });
            }
        };

        // Ban keys starting with `NEXTEST`.
        validate_env_var_key(key)?;

        env_map.insert(key.to_owned(), value.to_owned());
    }

    Ok(SetupScriptEnvMap { env_map })
}

// Given the comment at https://github.com/nextest-rs/nextest/pull/3001#discussion_r2907594583, the
// following regex is used to validate against the most conservative definition of a valid key.  Given
// that environment variables are defined as strings in the form of `name=value`, with the definition of
// "Name" taken from POSIX.1-2024, where it states [1]:
//
// > In the shell command language, a word consisting solely of underscores, digits, and alphabetics
// > from the portable character set. The first character of a name is not a digit.
//
// That said, this may be overly conservative as chapter 8 of POSIX.1-2024 simply have the definition
// of an environment variable started with the following [2]:
//
// > These strings have the form name=value; names shall not contain any bytes that have the encoded value
// > of the character '='.
//
// Under Windows, in Microsoft's own documentation on this topic, it simply states [3]:
//
// > The name of an environment variable cannot include an equal sign (=).
//
// The consensus seems to imply that the only character that cannot be present is the equal sign `=`.
// POSIX.1-2024 goes further to note that NUL would not be portable across systems that conform to the
// standard, though it does also state:
//
// > Other characters, and byte sequences that do not form valid characters, may be permitted by an
// > implementation; applications shall tolerate the presence of such names.
//
// So here for now, the implementation here chooses to be restrictive by not permitting other characters
// as it isn't wrong to do so, and that it also it restricts the use of '=' and NUL.
//
// Note that the regex pattern below is constructed to capture less than the minimally required number of
// characters, with the final group capturing the remainder with any unsupported characters.  The capture
// groups can then be leveraged to better disambiguate the kind of error to return.
//
// [1]: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap03.html#tag_03_216
// [2]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html.
// [3]: https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables
static ENV_KEY_VALIDATION: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^([a-zA-Z_]?)([a-zA-Z0-9_]*)(.*)$").unwrap());

/// Validates a str to see if it is suitable to be a key of an environment variable.
pub(crate) fn validate_env_var_key(key: &str) -> Result<(), EnvVarError> {
    if let Some(captures) = ENV_KEY_VALIDATION.captures(key) {
        let start = captures
            .get(1)
            .expect("regex had three defined capture groups");
        let tail = captures
            .get(3)
            .expect("regex had three defined capture groups");
        if start.is_empty() {
            Err(EnvVarError::InvalidKeyStartChar {
                key: key.to_owned(),
            })
        } else if !tail.is_empty() {
            Err(EnvVarError::InvalidKey {
                key: key.to_owned(),
            })
        } else if key.starts_with("NEXTEST") {
            Err(EnvVarError::ReservedKey {
                key: key.to_owned(),
            })
        } else {
            Ok(())
        }
    } else {
        // Multiline matching not enabled so failure to match with a newline will be handled here.
        Err(EnvVarError::InvalidKey {
            key: key.to_owned(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use test_case::test_case;

    #[test]
    fn validate_env_var_key_valid() {
        validate_env_var_key("MY_ENV_VAR").unwrap();
        validate_env_var_key("MY_ENV_VAR_1").unwrap();
        validate_env_var_key("__NEXTEST_TEST").unwrap();
    }

    #[test_case(
        "",
        "key `` does not start with a underscore or an alphabetic"

        ; "empty key"
    )]
    #[test_case(
        " ",
        "key ` ` does not start with a underscore or an alphabetic"

        ; "single space"
    )]
    #[test_case(
        "=",
        "key `=` does not start with a underscore or an alphabetic"

        ; "single equal sign"
    )]
    #[test_case(
        "0",
        "key `0` does not start with a underscore or an alphabetic"

        ; "single digit"
    )]
    #[test_case(
        "0TEST ",
        "key `0TEST ` does not start with a underscore or an alphabetic"

        ; "key started with a digit"
    )]
    #[test_case(
        "=TEST=",
        "key `=TEST=` does not start with a underscore or an alphabetic"

        ; "key started with an equal sign"
    )]
    #[test_case(
        "TEST TEST",
        "key `TEST TEST` does not consist solely of underscores, digits, and alphabetics"

        ; "key containing a space"
    )]
    #[test_case(
        "TESTTEST\n",
        "key `TESTTEST\n` does not consist solely of underscores, digits, and alphabetics"

        ; "key containing a newline"
    )]
    #[test_case(
        "TEST=TEST",
        "key `TEST=TEST` does not consist solely of underscores, digits, and alphabetics"

        ; "key containing an equal sign"
    )]
    #[test_case(
        "TEST=",
        "key `TEST=` does not consist solely of underscores, digits, and alphabetics"

        ; "key ending in an equal sign"
    )]
    #[test_case(
        "NEXTEST",
        "key `NEXTEST` begins with `NEXTEST`, which is reserved for internal use"

        ; "key is reserved"
    )]
    #[test_case(
        "NEXTEST_NEXTEST",
        "key `NEXTEST_NEXTEST` begins with `NEXTEST`, which is reserved for internal use"

        ; "key is also reserved"
    )]
    fn validate_env_var_key_invalid(key: &str, message: &str) {
        let err = validate_env_var_key(key).unwrap_err();
        let actual_message = err.to_string();

        assert_eq!(
            actual_message, message,
            "key validation error `{actual_message}` should equal to `{message}`"
        );
    }
}
