// Copyright (c) The nextest Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

use crate::{
    errors::{EnvVarError, SetupScriptOutputError},
    reporter::events::SetupScriptEnvMap,
};
use camino::Utf8Path;
use std::{collections::BTreeMap, sync::Arc};
use tokio::io::{AsyncBufReadExt, BufReader};

/// Parses an environment file generated by a setup script.
pub(super) async fn parse_env_file(
    env_path: &Utf8Path,
) -> Result<SetupScriptEnvMap, SetupScriptOutputError> {
    let mut env_map = BTreeMap::new();
    let f = tokio::fs::File::open(env_path).await.map_err(|error| {
        SetupScriptOutputError::EnvFileOpen {
            path: env_path.to_owned(),
            error: Arc::new(error),
        }
    })?;
    let reader = BufReader::new(f);
    let mut lines = reader.lines();
    loop {
        let line =
            lines
                .next_line()
                .await
                .map_err(|error| SetupScriptOutputError::EnvFileRead {
                    path: env_path.to_owned(),
                    error: Arc::new(error),
                })?;
        let Some(line) = line else { break };

        // Split this line into key and value.
        let (key, value) = match line.split_once('=') {
            Some((key, value)) => (key, value),
            None => {
                return Err(SetupScriptOutputError::EnvFileParse {
                    path: env_path.to_owned(),
                    line: line.to_owned(),
                });
            }
        };

        // Ban keys starting with `NEXTEST` and keys with invalid characters.
        validate_env_var_key(key).map_err(|error| SetupScriptOutputError::EnvFileInvalidKey {
            path: env_path.to_owned(),
            error,
        })?;

        env_map.insert(key.to_owned(), value.to_owned());
    }

    Ok(SetupScriptEnvMap { env_map })
}

// Validates against the most conservative definition of a valid environment
// variable key. The definition of "Name" is taken from POSIX.1-2024 [1]:
//
// > In the shell command language, a word consisting solely of underscores,
// > digits, and alphabetics from the portable character set. The first
// > character of a name is not a digit.
//
// This is more conservative than strictly necessary: chapter 8 of
// POSIX.1-2024 [2] and Microsoft's documentation [3] only prohibit '=' in
// keys, and POSIX notes that implementations may permit other characters.
// However, restricting to the portable character set is not wrong and avoids
// cross-platform surprises (e.g. shells that reject non-POSIX names, or NUL
// bytes that are not portable).
//
// [1]: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap03.html#tag_03_216
// [2]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html
// [3]: https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables

/// Validates a str to see if it is suitable to be a key of an environment variable.
pub(crate) fn validate_env_var_key(key: &str) -> Result<(), EnvVarError> {
    let mut chars = key.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => {
            return Err(EnvVarError::InvalidKeyStartChar {
                key: key.to_owned(),
            });
        }
    }
    if !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(EnvVarError::InvalidKey {
            key: key.to_owned(),
        });
    }
    if key.starts_with("NEXTEST") {
        return Err(EnvVarError::ReservedKey {
            key: key.to_owned(),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use test_case::test_case;

    #[test]
    fn validate_env_var_key_valid() {
        validate_env_var_key("MY_ENV_VAR").unwrap();
        validate_env_var_key("MY_ENV_VAR_1").unwrap();
        validate_env_var_key("__NEXTEST_TEST").unwrap();
    }

    #[test_case(
        "",
        "key `` does not start with a letter or underscore"

        ; "empty key"
    )]
    #[test_case(
        " ",
        "key ` ` does not start with a letter or underscore"

        ; "single space"
    )]
    #[test_case(
        "=",
        "key `=` does not start with a letter or underscore"

        ; "single equal sign"
    )]
    #[test_case(
        "0",
        "key `0` does not start with a letter or underscore"

        ; "single digit"
    )]
    #[test_case(
        "0TEST ",
        "key `0TEST ` does not start with a letter or underscore"

        ; "key started with a digit"
    )]
    #[test_case(
        "=TEST=",
        "key `=TEST=` does not start with a letter or underscore"

        ; "key started with an equal sign"
    )]
    #[test_case(
        "TEST TEST",
        "key `TEST TEST` does not consist solely of letters, digits, and underscores"

        ; "key containing a space"
    )]
    #[test_case(
        "TESTTEST\n",
        "key `TESTTEST\n` does not consist solely of letters, digits, and underscores"

        ; "key containing a newline"
    )]
    #[test_case(
        "TEST=TEST",
        "key `TEST=TEST` does not consist solely of letters, digits, and underscores"

        ; "key containing an equal sign"
    )]
    #[test_case(
        "TEST=",
        "key `TEST=` does not consist solely of letters, digits, and underscores"

        ; "key ending in an equal sign"
    )]
    #[test_case(
        "NEXTEST",
        "key `NEXTEST` begins with `NEXTEST`, which is reserved for internal use"

        ; "key is reserved"
    )]
    #[test_case(
        "NEXTEST_NEXTEST",
        "key `NEXTEST_NEXTEST` begins with `NEXTEST`, which is reserved for internal use"

        ; "key is also reserved"
    )]
    fn validate_env_var_key_invalid(key: &str, message: &str) {
        let err = validate_env_var_key(key).unwrap_err();
        let actual_message = err.to_string();

        assert_eq!(
            actual_message, message,
            "key validation error `{actual_message}` should equal to `{message}`"
        );
    }
}
