# This workflow file serves as an example for cargo-hakari CI integration.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: cargo hakari

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  workspace-hack-check:
    name: Check workspace-hack
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - name: Install cargo-hakari
        uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2.83.2
        with:
          tool: cargo-hakari
      - name: Check workspace-hack Cargo.toml is up-to-date
        run: cargo hakari generate --diff
      - name: Check all crates depend on workspace-hack
        run: cargo hakari manage-deps --dry-run
